---
- hosts: raspiosc
  become: yes
  vars:
    username: "{{ ansible_user }}"
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common

    - name: Download Docker install script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: "0755"

    - name: Run Docker install script
      command: sh /tmp/get-docker.sh

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes
    - name: Add user to docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: yes
