---
- hosts: raspiosc
  become: yes
  tasks:
    - name: Add new user
      user:
        name: new_user
        password: "{{ 'new_user' | password_hash('sha512') }}"
        create_home: yes
        shell: /bin/bash

    - name: Grant new user sudo privileges
      copy:
        dest: /etc/sudoers.d/new_user
        content: "new_user ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"

    - name: Disable auto login
      lineinfile:
        path: /etc/lightdm/lightdm.conf
        regexp: "^autologin-user=pi"
        line: "#autologin-user=pi"
